export { default as Dashboard } from "./dashboard.svg";
export { default as Inventory } from "./ic_outline-inventory.svg";
export { default as Logout } from "./Icon.svg";
export { default as People } from "./People.svg";
export { default as Purcahse } from "./purchase.svg";
export { default as Sales } from "./Sales (2).svg";
export { default as Export } from "./Export.svg";
export { default as Delete } from "./Delete.svg";
export { default as Edit } from "./Edit.svg";
export { default as View } from "./View.svg";
export { default as Logo } from "./Vector.svg";
